[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/ar/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Netlify-CDN-Cache-Control = "public, max-age=0, must-revalidate"
